# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7556ceac9cd38731b0ddb7404322075d5864326dbd687987b602edb3a6d73eefd5fcf99b600a2a6cc101b52d2cc808ff38cf077b2d35e8a3d4f3d4c463101a8c

test:
  secret_key_base: 4ff65ca0a495e529948d3c3c292f04c2f03f6f7d056dcf69efefc35bf412be28279d4888b98a8bc6cab8fda0fbead56b7a5d234fcc33354e21edf561bd2a9823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
